name: Combine Dependabot PRs

on:
  schedule:
    # Daily at 13:00 UTC (9:00 AM EDT / 8:00 AM EST)
    - cron: "0 13 * * *"

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  combine-dependabot-prs:
    uses: cloudgxp/reusable-workflows/.github/workflows/combine-dependabot-prs.yml@main
